### ISSUE TITLE
Default branch mismatch

### ISSUE THREAD

**Issue by derikvanschaik** [Edan184/Tag-Scanner#1]
Hey Edan, cool project! Your default branch is currently set as 'main' but the branch where all your work lies in is in 'master'.

**Comment by Edan184** [comment]
I'm aware and have no clue how to fix it.

**Comment by Edan184** [comment]
lol

**Comment by derikvanschaik** [comment]
@Edan184 try following these instructions and see if that helps https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by Edan184** [comment]
ʸᵃʸ
